name: Smart Test Runner - Predictive Fixer Integration

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

env:
  PREDICTIVE_FIXER_API: "https://5b208a58-8bfc-4b1a-926b-350b461ec857-00-ry1koupxp13c.sisko.replit.dev"
  REPO_ID: "gaming-hub-v1"

jobs:
  smart-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Collect all test names
        id: collect
        run: |
          if [ -d "tests" ] || find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
            TESTS=$(pytest --collect-only -q 2>/dev/null | grep "::" | sort -u | tr '\n' ',' | sed 's/,$//')
            if [ -z "$TESTS" ]; then
              TESTS=$(find . -name "test_*.py" -o -name "*_test.py" | sort -u | tr '\n' ',' | sed 's/,$//')
            fi
          else
            echo "No tests found, skipping..."
            TESTS=""
          fi
          echo "tests=$TESTS" >> $GITHUB_OUTPUT
          echo "Found tests: $TESTS"
      
      - name: Get changed files info
        id: changes
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            FILES=$(git diff --name-only HEAD~1 HEAD | tr '\n' '","' | sed 's/","$//' | sed 's/^/"/' | sed 's/$/"/')
            ADDED=$(git diff --stat HEAD~1 HEAD | tail -1 | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo "0")
            REMOVED=$(git diff --stat HEAD~1 HEAD | tail -1 | grep -oE '[0-9]+ deletion' | grep -oE '[0-9]+' || echo "0")
          else
            FILES='""'
            ADDED="0"
            REMOVED="0"
          fi
          echo "files=[$FILES]" >> $GITHUB_OUTPUT
          echo "added=${ADDED:-0}" >> $GITHUB_OUTPUT
          echo "removed=${REMOVED:-0}" >> $GITHUB_OUTPUT
          echo "Changed files: $FILES"
          echo "Lines added: $ADDED, removed: $REMOVED"
      
      - name: Call Predictive Fixer API
        id: prioritize
        if: steps.collect.outputs.tests != ''
        run: |
          TESTS_JSON=$(echo "${{ steps.collect.outputs.tests }}" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')
          
          RESPONSE=$(curl -s -X POST "${{ env.PREDICTIVE_FIXER_API }}/v1/prioritize" \
            -H "Content-Type: application/json" \
            -d '{
              "repo_id": "${{ env.REPO_ID }}",
              "commit_hash": "${{ github.sha }}",
              "commit_info": {
                "files_changed": ${{ steps.changes.outputs.files }},
                "lines_added": ${{ steps.changes.outputs.added }},
                "lines_removed": ${{ steps.changes.outputs.removed }},
                "author": "${{ github.actor }}"
              },
              "available_tests": ['"$TESTS_JSON"']
            }')
          
          echo "API Response:"
          echo "$RESPONSE" | jq '.' 2>/dev/null || echo "$RESPONSE"
          
          echo "$RESPONSE" > priority.json
          
          HIGH_RISK=$(echo "$RESPONSE" | jq -r '.prioritized_tests[] | select(.risk_score >= 0.5) | .test_id' 2>/dev/null | tr '\n' ' ')
          ALL_TESTS=$(echo "$RESPONSE" | jq -r '.prioritized_tests[].test_id' 2>/dev/null | tr '\n' ' ')
          
          echo "high_risk=$HIGH_RISK" >> $GITHUB_OUTPUT
          echo "all_tests=$ALL_TESTS" >> $GITHUB_OUTPUT
          echo ""
          echo "High-risk tests (run first): $HIGH_RISK"
          echo "All tests (prioritized): $ALL_TESTS"
      
      - name: Run high-risk tests first
        if: steps.prioritize.outputs.high_risk != ''
        run: |
          echo "Running HIGH-RISK tests first..."
          pytest ${{ steps.prioritize.outputs.high_risk }} -v --tb=short || true
      
      - name: Run remaining tests
        if: steps.prioritize.outputs.all_tests != ''
        run: |
          echo "Running all tests in priority order..."
          pytest ${{ steps.prioritize.outputs.all_tests }} -v
      
      - name: Run all tests (fallback)
        if: steps.collect.outputs.tests == '' || steps.prioritize.outputs.all_tests == ''
        run: |
          echo "Running all tests (no prioritization available)..."
          pytest -v || echo "No tests to run"
      
      - name: Report results back to Predictive Fixer
        if: always() && steps.prioritize.outputs.all_tests != ''
        run: |
          RESULTS='[]'
          if [ -f .pytest_cache/v/cache/lastfailed ]; then
            FAILED=$(cat .pytest_cache/v/cache/lastfailed 2>/dev/null | jq -r 'keys[]' | cut -d':' -f2)
          fi
          
          curl -s -X POST "${{ env.PREDICTIVE_FIXER_API }}/v1/test-results" \
            -H "Content-Type: application/json" \
            -d '{
              "repo_id": "${{ env.REPO_ID }}",
              "commit_hash": "${{ github.sha }}",
              "results": []
            }' || echo "Could not report results"
