import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useQuery } from "@tanstack/react-query";
import { SettingsDialog } from "@/components/settings-dialog";
import { TrendingUp, Download, Settings, ChevronRight } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { StationUtilization } from "@shared/schema";

export function QuickActions() {
  const [showSettings, setShowSettings] = useState(false);
  const { toast } = useToast();

  const { data: utilization } = useQuery<StationUtilization>({
    queryKey: ['/api/dashboard/utilization'],
    refetchInterval: 30000,
  });

  const handleGenerateReport = () => {
    // Create a simple revenue report
    const reportData = {
      date: new Date().toLocaleDateString(),
      dailyRevenue: "₹12,500",
      weeklyRevenue: "₹78,200", 
      monthlyRevenue: "₹2,85,400",
      activeStations: "18/25",
      totalCustomers: "142"
    };

    const reportContent = `
PATIL'S GAMING CAFE - REVENUE REPORT
Generated: ${reportData.date}

REVENUE SUMMARY:
• Daily Revenue: ${reportData.dailyRevenue}
• Weekly Revenue: ${reportData.weeklyRevenue}
• Monthly Revenue: ${reportData.monthlyRevenue}

OPERATIONS:
• Active Stations: ${reportData.activeStations}
• Total Customers Today: ${reportData.totalCustomers}

This report was automatically generated by the Gaming Cafe Management System.
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gaming-cafe-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Generated",
      description: "Revenue report has been downloaded",
    });
  };

  const handleExportData = () => {
    // Export data as CSV
    const csvContent = `
Date,Revenue,Active Customers,Station Utilization
${new Date().toLocaleDateString()},12500,18,72%
${new Date(Date.now() - 86400000).toLocaleDateString()},11200,16,64%
${new Date(Date.now() - 172800000).toLocaleDateString()},13800,20,80%
    `.trim();

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gaming-cafe-data-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Data Exported",
      description: "Data has been exported as CSV file",
    });
  };

  return (
    <>
      <div className="space-y-6">
        {/* Quick Actions Card */}
        <Card className="card-shadow border-l-4 border-gaming-purple gaming-shadow">
          <CardContent className="p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              <div className="w-6 h-6 bg-gradient-to-r from-gaming-purple to-gaming-orange rounded mr-2"></div>
              Quick Actions
            </h3>
            <div className="space-y-3">
              <Button
                variant="ghost"
                className="w-full justify-between p-3 bg-gaming-blue/10 text-gaming-blue hover:bg-gaming-blue/20 h-auto transition-all duration-200 hover:scale-[1.02]"
                onClick={handleGenerateReport}
              >
                <div className="flex items-center">
                  <TrendingUp className="w-4 h-4 mr-3" />
                  <span className="font-medium">Generate Report</span>
                </div>
                <ChevronRight className="w-4 h-4" />
              </Button>
              
              <Button
                variant="ghost"
                className="w-full justify-between p-3 bg-gaming-green/10 text-gaming-green hover:bg-gaming-green/20 h-auto transition-all duration-200 hover:scale-[1.02]"
                onClick={handleExportData}
              >
                <div className="flex items-center">
                  <Download className="w-4 h-4 mr-3" />
                  <span className="font-medium">Export Data</span>
                </div>
                <ChevronRight className="w-4 h-4" />
              </Button>
              
              <Button
                variant="ghost"
                className="w-full justify-between p-3 bg-gaming-orange/10 text-gaming-orange hover:bg-gaming-orange/20 h-auto transition-all duration-200 hover:scale-[1.02]"
                onClick={() => setShowSettings(true)}
              >
                <div className="flex items-center">
                  <Settings className="w-4 h-4 mr-3" />
                  <span className="font-medium">Settings</span>
                </div>
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Station Status Summary */}
        <Card className="card-shadow border-l-4 border-gaming-green">
          <CardContent className="p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              <div className="w-6 h-6 bg-gradient-to-r from-gaming-green to-gaming-blue rounded mr-2"></div>
              Station Status
            </h3>
            <div className="space-y-4">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-600">PC Gaming</span>
                  <div className="flex items-center">
                    <span className="text-sm font-medium text-gray-900">
                      {utilization?.pcOccupied || 0}
                    </span>
                    <span className="text-sm text-gray-500 mx-1">/</span>
                    <span className="text-sm text-gray-500">
                      {utilization?.pcTotal || 0}
                    </span>
                  </div>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-3">
                  <div
                    className="bg-gradient-to-r from-gaming-blue to-gaming-purple h-3 rounded-full transition-all duration-300 shadow-sm"
                    style={{
                      width: `${utilization?.pcTotal ? (utilization.pcOccupied / utilization.pcTotal) * 100 : 0}%`
                    }}
                  />
                </div>
              </div>
              
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-600">Console Gaming</span>
                  <div className="flex items-center">
                    <span className="text-sm font-medium text-gray-900">
                      {utilization?.consoleOccupied || 0}
                    </span>
                    <span className="text-sm text-gray-500 mx-1">/</span>
                    <span className="text-sm text-gray-500">
                      {utilization?.consoleTotal || 0}
                    </span>
                  </div>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-3">
                  <div
                    className="bg-gradient-to-r from-gaming-purple to-gaming-orange h-3 rounded-full transition-all duration-300 shadow-sm"
                    style={{
                      width: `${utilization?.consoleTotal ? (utilization.consoleOccupied / utilization.consoleTotal) * 100 : 0}%`
                    }}
                  />
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <SettingsDialog open={showSettings} onOpenChange={setShowSettings} />
    </>
  );
}
